name: Python security && format

on:
  push:
    branches:
      - master
      - main

jobs:
  scans:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: install
        run: |
          python3.11 -m pip install pylint
          python3.11 -m pip install bandit
      - name: bandit
        run: |
          find . -name '*.py'
          ls -la
          pwd
          python3 -m bandit ./C2/python/*/*.py
      - name: pylint
        run: |
          python3.11 -m pylint ./C2/python/*/*.py
